In [1]:
data=""""Machine Learning (ML) stands at the forefront of technological advancements, reshaping the way we interact with information, make decisions, and solve complex problems. Rooted in the broader field of Artificial Intelligence (AI), machine learning enables computers to learn and improve from experience without being explicitly programmed. This intricate dance of algorithms, data, and models has ushered in a new era of computing, where systems can autonomously adapt and evolve.In the realm of machine learning, supervised learning takes center stage. It involves training a model on a labeled dataset, where each input is paired with its corresponding output. The algorithm learns to map inputs to outputs by discerning patterns and relationships within the provided data. This foundational approach finds applications in tasks like image recognition, speech processing, and natural language understanding.Unsupervised learning, in contrast, delves into the exploration of unlabeled data. Without explicit output guidance, the algorithm seeks patterns, structures, or relationships within the data. Clustering, where similar data points are grouped together, and dimensionality reduction, simplifying complex datasets while retaining essential information, are common applications of unsupervised learning.Blurring the lines between supervision and autonomy, semi-supervised learning combines labeled and unlabeled data. Leveraging the labeled subset for supervised tasks and drawing insights from the unlabeled portion, this approach strives to strike a balance, optimizing learning efficiency and generalization.Inspired by behavioral psychology, reinforcement learning introduces the concept of an agent interacting with an environment. Through a system of rewards and penalties, the agent learns optimal strategies by trial and error. This approach has found success in training agents for tasks such as game playing, robotic control, and autonomous decision-making.At the forefront of machine learning's resurgence is deep learning. This subset revolves around deep neural networks, drawing inspiration from the human brain's neural structure. These networks, with multiple layers (deep layers), have exhibited remarkable capabilities in tasks like image and speech recognition, natural language processing, and even complex strategic games.In the domain of image analysis, Convolutional Neural Networks (CNNs) have emerged as a potent tool. Mimicking the visual perception of humans, CNNs use convolutional layers to extract hierarchical features, enabling them to recognize patterns with a high level of accuracy. Applications range from facial recognition to medical image analysis.One of the pitfalls in machine learning is overfitting. This occurs when a model learns the training data too well, capturing noise and outliers that may not represent the true underlying patterns. Striking a balance between capturing nuances and avoiding overfitting is a delicate art that requires careful consideration of model complexity, data size, and regularization techniques.On the flip side, underfitting transpires when a model is too simplistic to capture the inherent complexity of the data. It fails to learn the underlying patterns, resulting in poor performance on both the training and unseen data. Tuning model complexity and leveraging more sophisticated algorithms are strategies to combat underfitting.To gauge a model's effectiveness, cross-validation emerges as a reliable technique. It involves dividing the dataset into multiple subsets, training the model on different combinations of these subsets, and evaluating its performance across diverse scenarios. This methodology provides a robust assessment of a model's ability to generalize to new, unseen data.Various metrics come into play when assessing model performance. Accuracy, precision, recall, and the F1 score are commonly employed to measure the model's ability to correctly classify instances, minimize false positives and negatives, and strike a balance between precision and recall."""

In [2]:
data1="""Certainly! Here's an in-depth exploration of machine learning spanning approximately 5000 words:

---

## Understanding Machine Learning: Unraveling the Fabric of Intelligence

### Introduction

Machine Learning (ML) stands at the forefront of technological advancements, reshaping the way we interact with information, make decisions, and solve complex problems. Rooted in the broader field of Artificial Intelligence (AI), machine learning enables computers to learn and improve from experience without being explicitly programmed. This intricate dance of algorithms, data, and models has ushered in a new era of computing, where systems can autonomously adapt and evolve.

### Foundations of Machine Learning

#### 1. **Supervised Learning**

In the realm of machine learning, supervised learning takes center stage. It involves training a model on a labeled dataset, where each input is paired with its corresponding output. The algorithm learns to map inputs to outputs by discerning patterns and relationships within the provided data. This foundational approach finds applications in tasks like image recognition, speech processing, and natural language understanding.

#### 2. **Unsupervised Learning**

Unsupervised learning, in contrast, delves into the exploration of unlabeled data. Without explicit output guidance, the algorithm seeks patterns, structures, or relationships within the data. Clustering, where similar data points are grouped together, and dimensionality reduction, simplifying complex datasets while retaining essential information, are common applications of unsupervised learning.

#### 3. **Semi-Supervised Learning**

Blurring the lines between supervision and autonomy, semi-supervised learning combines labeled and unlabeled data. Leveraging the labeled subset for supervised tasks and drawing insights from the unlabeled portion, this approach strives to strike a balance, optimizing learning efficiency and generalization.

#### 4. **Reinforcement Learning**

Inspired by behavioral psychology, reinforcement learning introduces the concept of an agent interacting with an environment. Through a system of rewards and penalties, the agent learns optimal strategies by trial and error. This approach has found success in training agents for tasks such as game playing, robotic control, and autonomous decision-making.

### The Rise of Deep Learning

#### 1. **Deep Neural Networks**

At the forefront of machine learning's resurgence is deep learning. This subset revolves around deep neural networks, drawing inspiration from the human brain's neural structure. These networks, with multiple layers (deep layers), have exhibited remarkable capabilities in tasks like image and speech recognition, natural language processing, and even complex strategic games.

#### 2. **Convolutional Neural Networks (CNNs)**

In the domain of image analysis, Convolutional Neural Networks (CNNs) have emerged as a potent tool. Mimicking the visual perception of humans, CNNs use convolutional layers to extract hierarchical features, enabling them to recognize patterns with a high level of accuracy. Applications range from facial recognition to medical image analysis.

#### 3. **Recurrent Neural Networks (RNNs)**

For tasks involving sequential data, such as natural language processing and time series prediction, Recurrent Neural Networks (RNNs) take the spotlight. Their ability to retain memory of past inputs makes them adept at capturing temporal dependencies, offering solutions for speech recognition, language translation, and even predicting stock prices.

### The Art and Science of Feature Engineering

In the quest for model accuracy, feature engineering emerges as a critical player. It involves selecting, transforming, or creating relevant features (input variables) to enhance a model's performance. The art lies in understanding the intricacies of the data, teasing out meaningful patterns, and presenting them to the algorithm for optimal learning.

### The Dance of Overfitting and Underfitting

#### 1. **Overfitting**

One of the pitfalls in machine learning is overfitting. This occurs when a model learns the training data too well, capturing noise and outliers that may not represent the true underlying patterns. Striking a balance between capturing nuances and avoiding overfitting is a delicate art that requires careful consideration of model complexity, data size, and regularization techniques.

#### 2. **Underfitting**

On the flip side, underfitting transpires when a model is too simplistic to capture the inherent complexity of the data. It fails to learn the underlying patterns, resulting in poor performance on both the training and unseen data. Tuning model complexity and leveraging more sophisticated algorithms are strategies to combat underfitting.

### Evaluating Model Performance

#### 1. **Cross-Validation**

To gauge a model's effectiveness, cross-validation emerges as a reliable technique. It involves dividing the dataset into multiple subsets, training the model on different combinations of these subsets, and evaluating its performance across diverse scenarios. This methodology provides a robust assessment of a model's ability to generalize to new, unseen data.

#### 2. **Metrics for Evaluation**

Various metrics come into play when assessing model performance. Accuracy, precision, recall, and the F1 score are commonly employed to measure the model's ability to correctly classify instances, minimize false positives and negatives, and strike a balance between precision and recall.

### Ethical Dimensions: Bias and Fairness

The power of machine learning comes with ethical responsibilities. Models, when trained on biased data, can perpetuate and even exacerbate existing societal biases. Recognizing the importance of fairness, researchers and practitioners are actively working on developing methods to detect, mitigate, and prevent bias in machine learning algorithms.

### Continuous Learning: Deployment and Monitoring

#### 1. **Deployment Challenges**

Bringing a machine learning model into the real world introduces a new set of challenges. Integration into existing systems, scalability, and user acceptance are critical considerations. The transition from a controlled training environment to the unpredictability of real-world data requires meticulous planning and adaptation.

#### 2. **Continuous Monitoring**

The journey doesn't end with deployment. Continuous monitoring is indispensable to ensure a model's ongoing performance. Concept drift, wherein the statistical properties of the data evolve over time, necessitates adaptive strategies to maintain model relevance. Regular updates, feedback loops, and a keen eye on emerging trends characterize effective model maintenance.

### Future Frontiers and Closing Thoughts

As machine learning continues to advance, the future holds exciting possibilities. From the fusion of machine learning and other cutting-edge technologies like quantum computing to the exploration of explainable AI, the field is in a state of perpetual evolution. Navigating the ethical, social, and technical dimensions, the journey of machine learning reflects our collective endeavor to harness the power of intelligence in the digital age.

In conclusion, machine learning is not merely a technological pursuit; it is a journey of discovery, adaptation, and responsible innovation. The algorithms we craft today shape the landscapes of tomorrow, and the responsible use of this technology holds the key to a future where intelligence serves humanity with wisdom and equity.

---

I hope this provides a comprehensive overview of machine learning! If you have specific areas you'd like to delve deeper into or if there are particular aspects you'd like more information on, feel free to let me know."""

In [3]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [4]:
tokenizer=Tokenizer()

In [5]:
tokenizer.fit_on_texts([data])



In [6]:
tokenizer.word_index
#viewing number assign to every word

{'the': 1,
 'and': 2,
 'of': 3,
 'a': 4,
 'to': 5,
 'learning': 6,
 'data': 7,
 'in': 8,
 'this': 9,
 'model': 10,
 'machine': 11,
 'with': 12,
 'training': 13,
 'is': 14,
 'patterns': 15,
 'from': 16,
 'on': 17,
 'tasks': 18,
 'image': 19,
 'are': 20,
 'complex': 21,
 'where': 22,
 'supervised': 23,
 'it': 24,
 'labeled': 25,
 'learns': 26,
 'by': 27,
 'approach': 28,
 'applications': 29,
 'recognition': 30,
 'into': 31,
 'unlabeled': 32,
 'between': 33,
 'balance': 34,
 'as': 35,
 'deep': 36,
 'neural': 37,
 'networks': 38,
 'layers': 39,
 'when': 40,
 'complexity': 41,
 'performance': 42,
 "model's": 43,
 'at': 44,
 'forefront': 45,
 'information': 46,
 'learn': 47,
 'without': 48,
 'algorithms': 49,
 'has': 50,
 'new': 51,
 'involves': 52,
 'dataset': 53,
 'its': 54,
 'output': 55,
 'algorithm': 56,
 'relationships': 57,
 'within': 58,
 'like': 59,
 'speech': 60,
 'processing': 61,
 'natural': 62,
 'language': 63,
 'unsupervised': 64,
 'leveraging': 65,
 'subset': 66,
 'for': 67,
 

In [7]:
#for sentence in data.split('.'):
 #   tokenized_sentence=tokenizer.texts_to_sequences([sentence])[0]
  #  print(tokenized_sentence)

In [8]:
input_sequences = []
for sentence in data.split('.'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [48]:
len(tokenizer.word_index)


306

In [9]:
input_sequences

[[11, 6],
 [11, 6, 91],
 [11, 6, 91, 92],
 [11, 6, 91, 92, 44],
 [11, 6, 91, 92, 44, 1],
 [11, 6, 91, 92, 44, 1, 45],
 [11, 6, 91, 92, 44, 1, 45, 3],
 [11, 6, 91, 92, 44, 1, 45, 3, 93],
 [11, 6, 91, 92, 44, 1, 45, 3, 93, 94],
 [11, 6, 91, 92, 44, 1, 45, 3, 93, 94, 95],
 [11, 6, 91, 92, 44, 1, 45, 3, 93, 94, 95, 1],
 [11, 6, 91, 92, 44, 1, 45, 3, 93, 94, 95, 1, 96],
 [11, 6, 91, 92, 44, 1, 45, 3, 93, 94, 95, 1, 96, 97],
 [11, 6, 91, 92, 44, 1, 45, 3, 93, 94, 95, 1, 96, 97, 98],
 [11, 6, 91, 92, 44, 1, 45, 3, 93, 94, 95, 1, 96, 97, 98, 12],
 [11, 6, 91, 92, 44, 1, 45, 3, 93, 94, 95, 1, 96, 97, 98, 12, 46],
 [11, 6, 91, 92, 44, 1, 45, 3, 93, 94, 95, 1, 96, 97, 98, 12, 46, 99],
 [11, 6, 91, 92, 44, 1, 45, 3, 93, 94, 95, 1, 96, 97, 98, 12, 46, 99, 100],
 [11, 6, 91, 92, 44, 1, 45, 3, 93, 94, 95, 1, 96, 97, 98, 12, 46, 99, 100, 2],
 [11,
  6,
  91,
  92,
  44,
  1,
  45,
  3,
  93,
  94,
  95,
  1,
  96,
  97,
  98,
  12,
  46,
  99,
  100,
  2,
  101],
 [11,
  6,
  91,
  92,
  44,
  1,
  45

In [10]:
max_len=max([len(x) for x in input_sequences])
max_len

32

In [11]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

pad_sequences(input_sequences, maxlen=max_len, padding='pre')

In [12]:
padded_input_sequences=pad_sequences(input_sequences, maxlen=max_len, padding='pre')

In [13]:
padded_input_sequences

array([[ 0,  0,  0, ...,  0, 11,  6],
       [ 0,  0,  0, ..., 11,  6, 91],
       [ 0,  0,  0, ...,  6, 91, 92],
       ...,
       [ 0,  0, 79, ..., 34, 33, 89],
       [ 0, 79, 89, ..., 33, 89,  2],
       [79, 89, 90, ..., 89,  2, 90]])

In [14]:
x=padded_input_sequences[:,:-1]

In [15]:
x

array([[ 0,  0,  0, ...,  0,  0, 11],
       [ 0,  0,  0, ...,  0, 11,  6],
       [ 0,  0,  0, ..., 11,  6, 91],
       ...,
       [ 0,  0, 79, ...,  4, 34, 33],
       [ 0, 79, 89, ..., 34, 33, 89],
       [79, 89, 90, ..., 33, 89,  2]])

In [16]:
y=padded_input_sequences[:,-1]

In [17]:
 x.shape

(543, 31)

In [18]:
y.shape

(543,)

In [19]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=307)

In [20]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [21]:
y


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [27]:
y.shape

(543, 307)

In [22]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [62]:
model=Sequential()
model.add(Embedding(307,100,input_length=31))
model.add(LSTM(150))

model.add(Dense(307,activation='softmax'))


In [63]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [64]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_9 (Embedding)     (None, 31, 100)           30700     
                                                                 
 lstm_9 (LSTM)               (None, 150)               150600    
                                                                 
 dense_9 (Dense)             (None, 307)               46357     
                                                                 
Total params: 227657 (889.29 KB)
Trainable params: 227657 (889.29 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [65]:
model.fit(x,y,epochs=500)

Epoch 1/500
17/17 [==============================] - 2s 20ms/step - loss: 5.6875 - accuracy: 0.0497
Epoch 2/500
17/17 [==============================] - 0s 19ms/step - loss: 5.4489 - accuracy: 0.0368
Epoch 3/500
17/17 [==============================] - 0s 19ms/step - loss: 5.2934 - accuracy: 0.0534
Epoch 4/500
17/17 [==============================] - 0s 19ms/step - loss: 5.2592 - accuracy: 0.0534
Epoch 5/500
17/17 [==============================] - 0s 18ms/step - loss: 5.2371 - accuracy: 0.0681
Epoch 6/500
17/17 [==============================] - 0s 18ms/step - loss: 5.2143 - accuracy: 0.0737
Epoch 7/500
17/17 [==============================] - 0s 19ms/step - loss: 5.1738 - accuracy: 0.0681
Epoch 8/500
17/17 [==============================] - 0s 24ms/step - loss: 5.1197 - accuracy: 0.0773
Epoch 9/500
17/17 [==============================] - 0s 22ms/step - loss: 5.0593 - accuracy: 0.0700
Epoch 10/500
17/17 [==============================] - 0s 28ms/step - loss: 4.9662 - accuracy: 0.0755

17/17 [==============================] - 0s 23ms/step - loss: 0.1446 - accuracy: 0.9834
Epoch 83/500
17/17 [==============================] - 0s 24ms/step - loss: 0.1409 - accuracy: 0.9816
Epoch 84/500
17/17 [==============================] - 0s 23ms/step - loss: 0.1373 - accuracy: 0.9834
Epoch 85/500
17/17 [==============================] - 0s 23ms/step - loss: 0.1342 - accuracy: 0.9816
Epoch 86/500
17/17 [==============================] - 0s 23ms/step - loss: 0.1295 - accuracy: 0.9853
Epoch 87/500
17/17 [==============================] - 0s 23ms/step - loss: 0.1268 - accuracy: 0.9816
Epoch 88/500
17/17 [==============================] - 0s 26ms/step - loss: 0.1239 - accuracy: 0.9834
Epoch 89/500
17/17 [==============================] - 0s 23ms/step - loss: 0.1210 - accuracy: 0.9797
Epoch 90/500
17/17 [==============================] - 0s 22ms/step - loss: 0.1181 - accuracy: 0.9816
Epoch 91/500
17/17 [==============================] - 0s 22ms/step - loss: 0.1154 - accuracy: 0.9816
Epo

17/17 [==============================] - 0s 28ms/step - loss: 0.0484 - accuracy: 0.9834
Epoch 163/500
17/17 [==============================] - 0s 29ms/step - loss: 0.0486 - accuracy: 0.9797
Epoch 164/500
17/17 [==============================] - 1s 30ms/step - loss: 0.0484 - accuracy: 0.9816
Epoch 165/500
17/17 [==============================] - 0s 27ms/step - loss: 0.0480 - accuracy: 0.9816
Epoch 166/500
17/17 [==============================] - 1s 31ms/step - loss: 0.0477 - accuracy: 0.9816
Epoch 167/500
17/17 [==============================] - 1s 30ms/step - loss: 0.0481 - accuracy: 0.9853
Epoch 168/500
17/17 [==============================] - 0s 24ms/step - loss: 0.0471 - accuracy: 0.9816
Epoch 169/500
17/17 [==============================] - 0s 24ms/step - loss: 0.0466 - accuracy: 0.9834
Epoch 170/500
17/17 [==============================] - 0s 23ms/step - loss: 0.0464 - accuracy: 0.9834
Epoch 171/500
17/17 [==============================] - 0s 23ms/step - loss: 0.0467 - accuracy: 0

17/17 [==============================] - 0s 24ms/step - loss: 0.0367 - accuracy: 0.9834
Epoch 243/500
17/17 [==============================] - 0s 24ms/step - loss: 0.0366 - accuracy: 0.9834
Epoch 244/500
17/17 [==============================] - 1s 31ms/step - loss: 0.0364 - accuracy: 0.9853
Epoch 245/500
17/17 [==============================] - 0s 29ms/step - loss: 0.0359 - accuracy: 0.9834
Epoch 246/500
17/17 [==============================] - 1s 31ms/step - loss: 0.0365 - accuracy: 0.9816
Epoch 247/500
17/17 [==============================] - 0s 27ms/step - loss: 0.0364 - accuracy: 0.9816
Epoch 248/500
17/17 [==============================] - 0s 24ms/step - loss: 0.0356 - accuracy: 0.9853
Epoch 249/500
17/17 [==============================] - 0s 24ms/step - loss: 0.0357 - accuracy: 0.9816
Epoch 250/500
17/17 [==============================] - 0s 24ms/step - loss: 0.0359 - accuracy: 0.9797
Epoch 251/500
17/17 [==============================] - 0s 24ms/step - loss: 0.0359 - accuracy: 0

17/17 [==============================] - 0s 24ms/step - loss: 0.0346 - accuracy: 0.9797
Epoch 323/500
17/17 [==============================] - 0s 23ms/step - loss: 0.0345 - accuracy: 0.9816
Epoch 324/500
17/17 [==============================] - 0s 28ms/step - loss: 0.0337 - accuracy: 0.9834
Epoch 325/500
17/17 [==============================] - 0s 23ms/step - loss: 0.0342 - accuracy: 0.9816
Epoch 326/500
17/17 [==============================] - 0s 24ms/step - loss: 0.0345 - accuracy: 0.9816
Epoch 327/500
17/17 [==============================] - 0s 24ms/step - loss: 0.0333 - accuracy: 0.9834
Epoch 328/500
17/17 [==============================] - 0s 23ms/step - loss: 0.0339 - accuracy: 0.9816
Epoch 329/500
17/17 [==============================] - 0s 23ms/step - loss: 0.0340 - accuracy: 0.9797
Epoch 330/500
17/17 [==============================] - 0s 23ms/step - loss: 0.0332 - accuracy: 0.9816
Epoch 331/500
17/17 [==============================] - 0s 24ms/step - loss: 0.0333 - accuracy: 0

17/17 [==============================] - 0s 27ms/step - loss: 0.0312 - accuracy: 0.9816
Epoch 403/500
17/17 [==============================] - 0s 24ms/step - loss: 0.0315 - accuracy: 0.9816
Epoch 404/500
17/17 [==============================] - 0s 28ms/step - loss: 0.0311 - accuracy: 0.9834
Epoch 405/500
17/17 [==============================] - 0s 25ms/step - loss: 0.0310 - accuracy: 0.9816
Epoch 406/500
17/17 [==============================] - 0s 24ms/step - loss: 0.0309 - accuracy: 0.9834
Epoch 407/500
17/17 [==============================] - 0s 29ms/step - loss: 0.0310 - accuracy: 0.9834
Epoch 408/500
17/17 [==============================] - 0s 24ms/step - loss: 0.0318 - accuracy: 0.9797
Epoch 409/500
17/17 [==============================] - 0s 29ms/step - loss: 0.0311 - accuracy: 0.9834
Epoch 410/500
17/17 [==============================] - 0s 27ms/step - loss: 0.0313 - accuracy: 0.9797
Epoch 411/500
17/17 [==============================] - 0s 25ms/step - loss: 0.0307 - accuracy: 0

17/17 [==============================] - 0s 23ms/step - loss: 0.0303 - accuracy: 0.9816
Epoch 483/500
17/17 [==============================] - 0s 25ms/step - loss: 0.0305 - accuracy: 0.9834
Epoch 484/500
17/17 [==============================] - 0s 23ms/step - loss: 0.0301 - accuracy: 0.9816
Epoch 485/500
17/17 [==============================] - 0s 23ms/step - loss: 0.0306 - accuracy: 0.9797
Epoch 486/500
17/17 [==============================] - 0s 23ms/step - loss: 0.0301 - accuracy: 0.9816
Epoch 487/500
17/17 [==============================] - 0s 23ms/step - loss: 0.0305 - accuracy: 0.9816
Epoch 488/500
17/17 [==============================] - 0s 22ms/step - loss: 0.0304 - accuracy: 0.9816
Epoch 489/500
17/17 [==============================] - 0s 24ms/step - loss: 0.0308 - accuracy: 0.9797
Epoch 490/500
17/17 [==============================] - 0s 22ms/step - loss: 0.0302 - accuracy: 0.9816
Epoch 491/500
17/17 [==============================] - 0s 24ms/step - loss: 0.0303 - accuracy: 0

In [67]:
text='machine learning'

In [68]:
token_text=tokenizer.texts_to_sequences([text])[0]

In [71]:
padded_token_text=pad_sequences([token_text],maxlen=31,padding='pre')
padded_token_text

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11,  6]])

In [72]:
model.predict(padded_token_text)


1/1 [==============================] - 0s 311ms/step


array([[1.54904345e-09, 2.63778730e-07, 1.07488418e-08, 1.80018603e-07,
        4.45267823e-09, 7.75844988e-09, 7.68142399e-06, 7.47215623e-08,
        2.94602156e-04, 9.55981783e-09, 3.15631695e-07, 4.29531752e-07,
        6.48195555e-06, 5.49278099e-08, 5.37222377e-06, 1.05500875e-09,
        3.71707538e-05, 7.96506264e-11, 1.02361405e-07, 1.78804047e-08,
        6.67047146e-08, 2.76717458e-08, 4.55390182e-06, 2.15164328e-05,
        1.25076949e-09, 7.97352655e-08, 3.44423157e-08, 2.29978543e-08,
        1.48618994e-07, 2.66900919e-08, 2.27992544e-07, 4.86931754e-07,
        2.17114874e-07, 7.42495672e-07, 1.67164245e-07, 7.11457204e-09,
        3.04217747e-06, 1.65191508e-07, 3.22809137e-06, 2.71994736e-07,
        6.86817430e-07, 2.00174753e-07, 2.62800837e-10, 2.88488167e-07,
        6.30964269e-06, 3.53528640e-06, 9.37044398e-09, 3.09522505e-08,
        1.95673788e-08, 2.12814811e-07, 2.37905255e-07, 2.17464868e-09,
        1.02238474e-07, 7.05605574e-09, 1.38854892e-08, 9.821321

In [76]:
import numpy as np
position=np.argmax(model.predict(padded_token_text))

1/1 [==============================] - 0s 16ms/step


In [77]:
for word,index in tokenizer.word_index.items():
    if index==position:
        print(word)

ml


In [84]:
import time
text = "deep learning"

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text=pad_sequences([token_text],maxlen=31,padding='pre')
  # predict
  position = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == position:
      text = text + " " + word
      print(text)
      

1/1 [==============================] - 0s 17ms/step
deep learning ml
1/1 [==============================] - 0s 16ms/step
deep learning ml stands
1/1 [==============================] - 0s 17ms/step
deep learning ml stands at
1/1 [==============================] - 0s 17ms/step
deep learning ml stands at the
1/1 [==============================] - 0s 17ms/step
deep learning ml stands at the forefront
1/1 [==============================] - 0s 16ms/step
deep learning ml stands at the forefront of
1/1 [==============================] - 0s 19ms/step
deep learning ml stands at the forefront of technological
1/1 [==============================] - 0s 20ms/step
deep learning ml stands at the forefront of technological advancements
1/1 [==============================] - 0s 16ms/step
deep learning ml stands at the forefront of technological advancements reshaping
1/1 [==============================] - 0s 17ms/step
deep learning ml stands at the forefront of technological advancements reshaping the
